export const cards = [
  {
    order: 1,
    symbol: "🂢",
    suit: "spades",
    value: 2,
    colour: "black",
    name: "two",
  },
  {
    order: 2,
    symbol: "🂣",
    suit: "spades",
    value: 3,
    colour: "black",
    name: "three",
  },
  {
    order: 3,
    symbol: "🂤",
    suit: "spades",
    value: 4,
    colour: "black",
    name: "four",
  },
  {
    order: 4,
    symbol: "🂥",
    suit: "spades",
    value: 5,
    colour: "black",
    name: "five",
  },
  {
    order: 5,
    symbol: "🂦",
    suit: "spades",
    value: 6,
    colour: "black",
    name: "six",
  },
  {
    order: 6,
    symbol: "🂧",
    suit: "spades",
    value: 7,
    colour: "black",
    name: "seven",
  },
  {
    order: 7,
    symbol: "🂨",
    suit: "spades",
    value: 8,
    colour: "black",
    name: "eight",
  },
  {
    order: 8,
    symbol: "🂩",
    suit: "spades",
    value: 9,
    colour: "black",
    name: "nine",
  },
  {
    order: 9,
    symbol: "🂪",
    suit: "spades",
    value: 10,
    colour: "black",
    name: "ten",
  },
  {
    order: 10,
    symbol: "🂫",
    suit: "spades",
    value: 10,
    colour: "black",
    name: "jack",
  },
  {
    order: 11,
    symbol: "🂭",
    suit: "spades",
    value: 10,
    colour: "black",
    name: "queen",
  },
  {
    order: 12,
    symbol: "🂮",
    suit: "spades",
    value: 10,
    colour: "black",
    name: "king",
  },
  {
    order: 13,
    symbol: "🂡",
    suit: "spades",
    value: 11,
    colour: "black",
    name: "ace",
  },
  {
    order: 1,
    symbol: "🂲",
    suit: "hearts",
    value: 2,
    colour: "red",
    name: "two",
  },
  {
    order: 2,
    symbol: "🂳",
    suit: "hearts",
    value: 3,
    colour: "red",
    name: "three",
  },
  {
    order: 3,
    symbol: "🂴",
    suit: "hearts",
    value: 4,
    colour: "red",
    name: "four",
  },
  {
    order: 4,
    symbol: "🂵",
    suit: "hearts",
    value: 5,
    colour: "red",
    name: "five",
  },
  {
    order: 5,
    symbol: "🂶",
    suit: "hearts",
    value: 6,
    colour: "red",
    name: "six",
  },
  {
    order: 6,
    symbol: "🂷",
    suit: "hearts",
    value: 7,
    colour: "red",
    name: "seven",
  },
  {
    order: 7,
    symbol: "🂸",
    suit: "hearts",
    value: 8,
    colour: "red",
    name: "eight",
  },
  {
    order: 8,
    symbol: "🂹",
    suit: "hearts",
    value: 9,
    colour: "red",
    name: "nine",
  },
  {
    order: 9,
    symbol: "🂺",
    suit: "hearts",
    value: 10,
    colour: "red",
    name: "ten",
  },
  {
    order: 10,
    symbol: "🂻",
    suit: "hearts",
    value: 10,
    colour: "red",
    name: "jack",
  },
  {
    order: 11,
    symbol: "🂽",
    suit: "hearts",
    value: 10,
    colour: "red",
    name: "queen",
  },
  {
    order: 12,
    symbol: "🂾",
    suit: "hearts",
    value: 10,
    colour: "red",
    name: "king",
  },
  {
    order: 13,
    symbol: "🂱",
    suit: "hearts",
    value: 11,
    colour: "red",
    name: "ace",
  },
  {
    order: 1,
    symbol: "🃂",
    suit: "diamonds",
    value: 2,
    colour: "red",
    name: "two",
  },
  {
    order: 2,
    symbol: "🃃",
    suit: "diamonds",
    value: 3,
    colour: "red",
    name: "three",
  },
  {
    order: 3,
    symbol: "🃄",
    suit: "diamonds",
    value: 4,
    colour: "red",
    name: "four",
  },
  {
    order: 4,
    symbol: "🃅",
    suit: "diamonds",
    value: 5,
    colour: "red",
    name: "five",
  },
  {
    order: 5,
    symbol: "🃆",
    suit: "diamonds",
    value: 6,
    colour: "red",
    name: "six",
  },
  {
    order: 6,
    symbol: "🃇",
    suit: "diamonds",
    value: 7,
    colour: "red",
    name: "seven",
  },
  {
    order: 7,
    symbol: "🃈",
    suit: "diamonds",
    value: 8,
    colour: "red",
    name: "eight",
  },
  {
    order: 8,
    symbol: "🃉",
    suit: "diamonds",
    value: 9,
    colour: "red",
    name: "nine",
  },
  {
    order: 9,
    symbol: "🃊",
    suit: "diamonds",
    value: 10,
    colour: "red",
    name: "ten",
  },
  {
    order: 10,
    symbol: "🃋",
    suit: "diamonds",
    value: 10,
    colour: "red",
    name: "jack",
  },
  {
    order: 11,
    symbol: "🃍",
    suit: "diamonds",
    value: 10,
    colour: "red",
    name: "queen",
  },
  {
    order: 12,
    symbol: "🃎",
    suit: "diamonds",
    value: 10,
    colour: "red",
    name: "king",
  },
  {
    order: 13,
    symbol: "🃁",
    suit: "diamonds",
    value: 11,
    colour: "red",
    name: "ace",
  },
  {
    order: 1,
    symbol: "🃒",
    suit: "clubs",
    value: 2,
    colour: "black",
    name: "two",
  },
  {
    order: 2,
    symbol: "🃓",
    suit: "clubs",
    value: 3,
    colour: "black",
    name: "three",
  },
  {
    order: 3,
    symbol: "🃔",
    suit: "clubs",
    value: 4,
    colour: "black",
    name: "four",
  },
  {
    order: 4,
    symbol: "🃕",
    suit: "clubs",
    value: 5,
    colour: "black",
    name: "five",
  },
  {
    order: 5,
    symbol: "🃖",
    suit: "clubs",
    value: 6,
    colour: "black",
    name: "six",
  },
  {
    order: 6,
    symbol: "🃗",
    suit: "clubs",
    value: 7,
    colour: "black",
    name: "seven",
  },
  {
    order: 7,
    symbol: "🃘",
    suit: "clubs",
    value: 8,
    colour: "black",
    name: "eight",
  },
  {
    order: 8,
    symbol: "🃙",
    suit: "clubs",
    value: 9,
    colour: "black",
    name: "nine",
  },
  {
    order: 9,
    symbol: "🃚",
    suit: "clubs",
    value: 10,
    colour: "black",
    name: "ten",
  },
  {
    order: 10,
    symbol: "🃛",
    suit: "clubs",
    value: 10,
    colour: "black",
    name: "jack",
  },
  {
    order: 11,
    symbol: "🃝",
    suit: "clubs",
    value: 10,
    colour: "black",
    name: "queen",
  },
  {
    order: 12,
    symbol: "🃞",
    suit: "clubs",
    value: 10,
    colour: "black",
    name: "king",
  },
  {
    order: 13,
    symbol: "🃑",
    suit: "clubs",
    value: 11,
    colour: "black",
    name: "ace",
  },
];
